version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-catwave
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CatWave
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catwave-backend
    ports:
      - "1212:1212"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
      SPRING_SESSION_JDBC_INITIALIZE_SCHEMA: ${SPRING_SESSION_JDBC_INITIALIZE_SCHEMA}
      SPRING_SESSION_JDBC_TABLE_NAME: ${SPRING_SESSION_JDBC_TABLE_NAME}
      SPRING_SESSION_JDBC_CREATE_TABLE: ${SPRING_SESSION_JDBC_CREATE_TABLE}



volumes:
  mysql_data:
